Further work on automating the build process for release

diff --git a/aquamacs/build/notarize-release b/aquamacs/build/notarize-release
--- a/aquamacs/build/notarize-release
+++ b/aquamacs/build/notarize-release
@@ -9,8 +9,45 @@ ZIPFILE=/tmp/aquamacs-to-notarize.zip
 cd nextstep
 ditto -c -k --keepParent Aquamacs.app "${ZIPFILE}"
 
+echo "Submitting for notarization..."
+
+TMPFILE=$(mktemp)
+
 xcrun altool --notarize-app \
       --primary-bundle-id "org.aquamacs.aquamacs36" \
-      --username "${AQUAMACS_NOTARIZE_ID}" \
-      --password "@keychain:AC_PASSWORD" \
-      --file ${ZIPFILE}
+      --username "${AQUAMACS_NOTARIZE_ID}"\
+      --password "@keychain:AC_PASSWORD"\
+      --file ${ZIPFILE} > "${TMPFILE}"
+
+cat ${TMPFILE}
+requestID=$(awk '/RequestUUID/ { print $NF; }' "${TMPFILE}")
+
+echo "Submission successful; request ID is ${requestID}"
+
+# XXX     --file /Users/wtreese/local/aquamacs-devel/Aquamacs-3.6-beta.dmg
+
+# If given --auto-staple, waits for the notarization process to finish
+# and then staples it to the app.
+
+if [ "$1"x = "--auto-staple"x ]; then
+    status="in progress"
+
+    while [[ "$status" == "in progress" ]]; do
+        sleep 15
+
+        status=$(xcrun altool --notarization-info "${requestID}" \
+                       --username "${AQUAMACS_NOTARIZE_ID}" \
+                       --password "@keychain:AC_PASSWORD" \
+                     | awk -F': ' '/Status:/ {print $2}')
+        echo -n '.'
+    done
+    echo 'finished'
+
+    if [[ "$status"x == "success"x ]]; then
+        xcrun stapler staple Aquamacs.app
+        echo "Notarization done and stapled"
+    else
+        echo "Notarization failed: status was ${status}"
+        exit 1
+    fi
+fi
